---
include:
- board: nice_nano_v2 
  shield: cradio_left
  snippet: zmk-usb-logging
- board: nice_nano_v2 
  shield: cradio_right
  snippet: zmk-usb-logging
- board: nice_nano_v2
  shield: settings_reset

- board: raytac_mdbt50q_rx 
  shield: settings_reset
- board: raytac_mdbt50q_rx
  shield: cradio_dongle
