---
include:
# - board: nice_nano_v2 
#   shield: cradio_left 
# - board: nice_nano_v2 
#   shield: cradio_right
# - board: nice_nano_v2
#   shield: settings_reset
# - board: raytac_mdbt50q_rx
#   shield: cradio_dongle

- board: nice_nano_v2
  shield: cradio_dongle
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=y
