---
include:
- board: nice_nano_v2 
  shield: cradio_left 
- board: nice_nano_v2 
  shield: cradio_right
- board: raytac_mdbt50q_rx
  shield: cradio_dongle
  - board: nice_nano_v2
    shield: settings_reset
