# board: [ "nice_nano_v2" ]
# shield: [ "cradio_left", "cradio_right" ]

---
include:
- board: nice_nano_v2 
  shield: cradio_left 
- board: nice_nano_v2 
  shield: cradio_right

#  # Config settings for the dongle
#  - board: raytac_mdbt50q_rx
#    shield: my_keyboard_dongle
#    
#  - board: raytac_mdbt50q_rx
#    shield: settings_reset
