# board: [ "nice_nano_v2" ]
# shield: [ "cradio_left", "cradio_right" ]

include:
#  # Config settings for the dongle
#  - board: raytac_mdbt50q_rx
#    shield: my_keyboard_dongle
#    
#  - board: raytac_mdbt50q_rx
#    shield: settings_reset
#
- board: nice_nano_v2
  shield:
    - cradio_left
    - cradio_right
